/* Make a modular code (Using the SIZE constant). It makes life easier when you are
 * dealing with projects, meaning that if you want to change the size of the table, you 
 * do not need to change everywhere you use the table in the code, you only need to change 
 * the value of SIZE. I also like to use the standard int variables. This is very usefull 
 * when we are dealing with code portability, once some integer values may vary from 
 * a 32x architecture to 64x.
 * Read more: http://pubs.opengroup.org/onlinepubs/009695399/basedefs/stdint.h.html
 */

#include <stdio.h>
#include <stdint.h>

#define	SIZE 	100
uint16_t table[SIZE];

/* Functions prototype */
uint16_t simpleHashing(uint16_t x);
void hashInsert(uint16_t value);
uint16_t getValue(uint16_t key);
	
main(){
	uint16_t i;

	printf("Simple Hash Function:\n");

	/* Initializing table with zeroes. */
	for(i = 0; i < SIZE; i++)
		table[i] = 0;
			
	/* Now we add the values 10, 1 and 0. */
	printf("Adding the values 10, 1 and 100...\n");
	hashInsert(10);  //Index is 10
	hashInsert(1);	 //Index is 1
	hashInsert(100); //Index is 0

	//Now we print the values of the indexes
	/*
		for(i = 0; i < SIZE; i++)
			printf("Tab[%d]\t: %d\n", i, table[i]);
	*/
		
	/* Now printing only the added values. */
	printf("Tab[0]\t: %d\n", getValue(0));
	printf("Tab[1]\t: %d\n", getValue(1));
	printf("Tab[10]\t: %d\n", getValue(10));

}

/* simpleHashing(): Calculates a simple hashing key
 * @x			  :	The data to be added
 * @key 		  : The generated key, meaning the index.
 */
uint16_t simpleHashing(uint16_t x){

	uint16_t key;
	key = x % SIZE;

	return key;
} 

/* hashInsert(): Calculate the data hashing and then insert
 *				 on the table.
 * @value 	   : the data to be inserted
 */
void hashInsert(uint16_t value){

	uint16_t key;
	/* Calculating the key. */
	key = simpleHashing(value);

	/* Adding the key on table. */
	table[key] = value;

	return;
}

/* getValue(): Return the value in the table given a key.
 * @key 	 : Index generated by a hashing function.
 */
uint16_t getValue(uint16_t key){
 	return table[key]; 
}
